### ISSUE TITLE
Add Tests for Sensory Milling Head

### ISSUE THREAD

**Issue by sanssecours** [MyTooliT/ICOc#24]
# Description

We need (hardware) tests for the new “Sensory Milling Head” (SMH). Since this hardware is similar to the STH, the holder and milling head test will share some code.

# Todo

- [x] Add command line script to run test
- [x] Add EEPROM test
- [x] Add connection test
- [x] Add test for „stationary“ value
- [ ] Add power consumption test

**Comment by sanssecours** [comment]
While the power consumption test is rather basic as of now – most power is probably consumed by the constantly glowing green LED on the PCB – it should still serve its purpose. The other tests should more or less work as expected.
