### ISSUE TITLE
SMH Test: Add Channel Test

### ISSUE THREAD

**Issue by sanssecours** [MyTooliT/ICOc#36]
# Description

At the moment we have to check if the different channels of a Sensory Milling Head work manually with ICOc. To improve this situation we should add automatic tests. The problem here is that the type of channels can be different for each SMH. Currently we think it should be possible to do a heuristic check and tell the test user if a sensor channel seems to be connected to

- an acceleration sensor: measured values should be around half of max value (between -1 g and 1 g)
- a temperature sensor: measured values should be something that reflects the normal room temperature
- a piezo sensor: measured values should be around half of max value (if I remember correctly)

or if the sensor seems to be broken.

# ToDo

- [x] Improve reading of streaming data in `Network` class
  - [x] Pay attention to message id when reading multiple messages 
  - [x] Merge current coroutines 

# External Links

[Jour Fixe Automatisierung-Team 2022 KW 36](https://mytoolit.bitrix24.de/company/personal/user/74/tasks/task/view/6431/)
