### ISSUE TITLE
Support User Accessible Configuration

### ISSUE THREAD

**Issue by sanssecours** [MyTooliT/ICOc#42]
# Description

Currently changing the configuration (mainly used for “hardware” tests) requires editing a YAML config file located inside the package. While this might be okay, when we clone the repository and use `pip -e` (editable source) to install the package it is certainly less from ideal:

- We need to be aware where the package (config file) is stored on our machine
- If we use `pip` without the `-e` option the config file might be stored inside an archive or another location that is hard to access

For that reason and as [preparation for uploading the package to PyPI](https://github.com/MyTooliT/ICOc/issues/37) we should make it possible to store the configuration at a location that is easier to access.

# ToDo

- [x] Read documentation from repo, site (global) and user config
- [x] Add CLI tool to open (and create) config files
- [x] Validate configuration (to make sure we do not store incorrect values)
- [x] Fix configuration values that depend on repo location
     - [x] Path to firmware
     - [x] Path to log files
- [x] Change all configuration keys to lowercase
- [x] Update default values, if it makes sense
- [x] Update documentation
