### ISSUE TITLE
ICOn: Do not Overwrite Old Measurement Data

### ISSUE THREAD

**Issue by sanssecours** [MyTooliT/ICOc#48]
# Description

Currently the `icon` subcommand `measure` always stores measurement data in a file called `Measurement.hdf5`. This is problematic since this means taking another measurement will not be possible, if this file exists. We should add a timestamp to the filename, just like we do for `icoc`, to make sure that `icon` does not corrupt old measurement data.

# Todo

- [x] Read measurement filename (`measurement.output.filename` from config file
- [x] Use config measurement directory (`measurement.output.directory`)
- [x] Append timestamp to measurement filename
